### ISSUE TITLE
Crashing at save

### ISSUE THREAD

**Issue by Emilianenko** [hjnilsson/rme#188] opened 2017-05-01 00:53 UTC
when i use the toll remove all unreachable tiles ,and try to save the map, he crashes at 99%  =(

**Comment by bpawel10** [comment] 2017-12-21 12:25
I can confirm I have the same issue.

**Comment by Costallat** [comment] 2018-08-07 01:03
The problem is when it removes some tile that have some creature or spawn on it.

**Comment by Costallat** [comment] 2018-08-09 00:28
@hjnilsson can you give me permission to commit?

I have a small fix for this.

Tks.

**Comment by hjnilsson** [comment] 2018-08-09 11:35
Added as a contributor. :)

**Comment by bpawel10** [comment] 2018-08-09 11:38
Why doesn't he just create pull request?

**Comment by bpawel10** [comment] 2018-08-09 12:25
So you probably did it wrong way. As far as I know you should fork this repo and push your branch there.

**Comment by gpedro** [comment] 2018-08-09 13:28
@dalkon fork this repository, if already cloned the project, change origin url to fork url and push your branch.

**Comment by Costallat** [comment] 2018-08-09 20:57
@bpawel10 So it's not that I did it wrong, I just didn't followed the Github process.

@gpedro Thanks for the explanation.

So I created a file to be used to reproduce the problem, you can open that map, clean it with the "unreachable tile" feature, and it will crash when you save it.

[crash.map.tar.gz](https://github.com/hjnilsson/rme/files/2275856/crash.map.tar.gz)

#236 

This is a v.0.1 version to the fix, as it doesn't show any message to inform the user that his map has those wrong spawn points, but it avoids the crash.

**Closed** 2019-06-01 02:48 UTC
Labels: bug, unconfirmed
